[category]
symbols = [ "BTCUSDT", "ETHUSDT"]

[specify.symbol1]
symbol = "ETHUSDT"
support_position = 1218
resistance_point = 1280

[specify.symbol2]
symbol = "BTCUSDT"
support_position = 16690
resistance_point = 30000
